# Generated by Django 4.1.3 on 2022-11-13 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Correspondencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Residencias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('numero', models.IntegerField()),
                ('cantidad_correo', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Carrera',
        ),
        migrations.AddField(
            model_name='correspondencia',
            name='residencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.residencias'),
        ),
    ]
