# Generated by Django 4.1.3 on 2022-11-13 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_correspondencia_residencias_delete_carrera_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='correspondencia',
            name='estado',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
