# Generated by Django 4.1.3 on 2022-11-13 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_correspondencia_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='residencias',
            name='cantidad_correo',
        ),
    ]
