# Generated by Django 4.1.3 on 2022-11-13 16:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0004_remove_residencias_cantidad_correo'),
    ]

    operations = [
        migrations.AddField(
            model_name='correspondencia',
            name='conserje',
            field=models.ForeignKey(default=0, limit_choices_to={'groups__name': 'Conserjes'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='correspondencia',
            name='estado',
            field=models.CharField(choices=[('re', 'Recibido'), ('en', 'Entregado')], default='re', max_length=2),
        ),
        migrations.AlterField(
            model_name='residencias',
            name='numero',
            field=models.PositiveIntegerField(),
        ),
    ]
