# Generated by Django 4.1.3 on 2022-11-13 16:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0005_correspondencia_conserje_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correspondencia',
            name='conserje',
            field=models.ForeignKey(limit_choices_to={'groups__name': 'Conserjes'}, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
