# Generated by Django 4.1.3 on 2022-11-13 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_correspondencia_conserje_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='residencias',
            name='numero',
            field=models.IntegerField(default=0),
        ),
    ]
