# Generated by Django 4.1.3 on 2022-11-13 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_rename_numero_residencias_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='residencias',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
