# Generated by Django 4.1.3 on 2022-11-13 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_residencias_numero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='residencias',
            name='numero',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
